-- Catálogos iniciales. Seguro para volver a ejecutar.
-- Los nombres se conservan como claves estables porque el generador de resguardos
-- los utiliza para ubicar cada elemento en el formato institucional.

INSERT INTO item_condicion (nombre, estado_default, activo) VALUES
('carroceria', 'bueno', TRUE),
('pintura', 'bueno', TRUE),
('vestidura', 'bueno', TRUE),
('direccion', 'bueno', TRUE),
('motor', 'bueno', TRUE),
('sistema_electrico', 'bueno', TRUE),
('sistema_encendido', 'bueno', TRUE),
('sistema_frenos', 'bueno', TRUE),
('sistema_suspension', 'bueno', TRUE),
('sistema_transmision', 'bueno', TRUE)
ON CONFLICT (nombre) DO UPDATE
SET estado_default = EXCLUDED.estado_default,
    activo = EXCLUDED.activo;

INSERT INTO item_inventario (nombre, categoria, estado_default, activo) VALUES
('tapon_gasolina', 'pieza', 'correcto', TRUE),
('estereo', 'pieza', 'correcto', TRUE),
('calefaccion', 'pieza', 'correcto', TRUE),
('aire_acondicionado', 'pieza', 'correcto', TRUE),
('consola_bateria_auxiliar', 'equipo_especial', 'na', TRUE),
('tapon_radiador', 'pieza', 'correcto', TRUE),
('radio_am_fm', 'pieza', 'correcto', TRUE),
('cenicero', 'pieza', 'correcto', TRUE),
('juego_herramientas', 'pieza', 'correcto', TRUE),
('radio_trans_antena', 'equipo_especial', 'na', TRUE),
('tapon_aceite', 'pieza', 'correcto', TRUE),
('antena', 'pieza', 'correcto', TRUE),
('encendedor', 'pieza', 'na', TRUE),
('extinguidor', 'pieza', 'correcto', TRUE),
('estrobos_faros_calaveras', 'equipo_especial', 'na', TRUE),
('tapones_rines', 'pieza', 'correcto', TRUE),
('alarma', 'pieza', 'correcto', TRUE),
('visera_derecha', 'pieza', 'correcto', TRUE),
('bayoneta_aceite', 'pieza', 'correcto', TRUE),
('camara_frontal_trasera', 'equipo_especial', 'na', TRUE),
('emblemas', 'pieza', 'correcto', TRUE),
('llave_puertas', 'pieza', 'na', TRUE),
('visera_izquierda', 'pieza', 'correcto', TRUE),
('bateria', 'pieza', 'correcto', TRUE),
('tumbaburros_sirena_altavoz', 'equipo_especial', 'na', TRUE),
('parrillas', 'pieza', 'correcto', TRUE),
('llave_tapon_gasolina', 'pieza', 'na', TRUE),
('cinturon_seguridad', 'pieza', 'correcto', TRUE),
('juego_placas', 'pieza', 'correcto', TRUE),
('sistema_grabacion', 'equipo_especial', 'na', TRUE),
('limpiadores', 'pieza', 'correcto', TRUE),
('llave_cajuela', 'pieza', 'na', TRUE),
('tapetes', 'pieza', 'correcto', TRUE),
('tarjeta_circulacion', 'pieza', 'correcto', TRUE),
('espejo_lateral_izquierdo', 'pieza', 'correcto', TRUE),
('llave_guantera', 'pieza', 'na', TRUE),
('alfombra_cajuela', 'pieza', 'correcto', TRUE),
('poliza_seguro', 'pieza', 'correcto', TRUE),
('espejo_lateral_derecho', 'pieza', 'correcto', TRUE),
('llave_encendido', 'pieza', 'correcto', TRUE),
('llanta_refaccion', 'pieza', 'correcto', TRUE),
('poliza_servicio', 'pieza', 'correcto', TRUE),
('espejo_retrovisor', 'pieza', 'correcto', TRUE),
('sistema_alarma', 'pieza', 'na', TRUE),
('gato', 'pieza', 'correcto', TRUE),
('verificacion', 'pieza', 'correcto', TRUE),
('llantas', 'pieza', 'correcto', TRUE),
('seguro_aletas', 'pieza', 'na', TRUE),
('llave_birlos', 'pieza', 'correcto', TRUE),
('revista_vehicular', 'pieza', 'correcto', TRUE),
('claxon', 'pieza', 'correcto', TRUE),
('seguro_puertas', 'pieza', 'na', TRUE),
('defroster', 'pieza', 'correcto', TRUE),
('reflejantes', 'pieza', 'correcto', TRUE)
ON CONFLICT (nombre) DO UPDATE
SET categoria = EXCLUDED.categoria,
    estado_default = EXCLUDED.estado_default,
    activo = EXCLUDED.activo;
